/*
 * layout.h
 *
 * Created: 3/15/2022 11:32:22 AM
 *  Author: alden
 */ 


#ifndef LAYOUT_H_
#define LAYOUT_H_



#include <stdint.h>
#include "keys.h"

#define NUM_LAYERS 3

const uint16_t key_array[3][3][16] = {
	{
		{KEY_ESC, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_BACKSPACE, KEY_TAB, KEY_A, KEY_S, KEY_D},
		{KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_LEFTSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M},
		{KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_ENTER,KEY_LEFTCTRL, KEY_CAPSLOCK, KEY_LEFTALT, KEY_LAYER_UP, KEY_SPACE, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_EQUAL, KEY_MINUS, KEY_DELETE, KEY_RIGHTCTRL, KEY_QUICK_FN},
	},
	{
		{KEY_GRAVE, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_BACKSLASH, KEY_TAB, KEY_A, KEY_S, KEY_D},
		{KEY_F, KEY_G, KEY_LEFT, KEY_DOWN, KEY_UP, KEY_RIGHT, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_LEFTSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M},
		{KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_ENTER, KEY_LEFTCTRL, KEY_CAPSLOCK, KEY_LEFTALT, KEY_LAYER_UP, KEY_SPACE, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_EQUAL, KEY_MINUS, KEY_DELETE, KEY_RIGHTCTRL, KEY_NONE},
	},
	{
		{KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12, KEY_VOLUMEDOWN, KEY_VOLUMEUP, KEY_MUTE, KEY_D},
		{KEY_F, KEY_G, KEY_H, KEY_DOWN, KEY_UP, KEY_RIGHT, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_LEFTSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M},
		{KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_ENTER,KEY_LEFTCTRL, KEY_CAPSLOCK, KEY_LEFTALT, KEY_NONE, KEY_SPACE, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_EQUAL, KEY_MINUS, KEY_DELETE, KEY_RIGHTCTRL, KEY_QUICK_FN},
	},
	};
	
uint16_t led_pressed_array[3][3][16] = {};
uint16_t led_base_array[3][3][16] = {};
#endif /* LAYOUT_H_ */